### PR TITLE
Update php5 to php7

### PR DESCRIPTION
**Pull request by Wouter0100**
Updated all php5 to php7, because php5 is not available in Ubuntu 16.04 repo anymore.

### CODE REVIEW

**Comment by Marlinc** [comment]
php5 is still available in the Ubuntu 16.04 repositories?

`
PHP 5.6.17-3ubuntu1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
`

**Comment by Wouter0100** [comment]
```
$ sudo apt-cache search php5
bluefish - advanced Gtk+ text editor for web and software development
phing - PHP5 project build system based on Apache Ant
php-auth - Creating an authentication system
php-doc - Documentation for PHP5
php-http-request2 - Provides an easy way to perform HTTP requests
php-letodms-lucene - Document management system - Fulltext search
php-memcache - memcache extension module for PHP5
php-memcached - memcached extension module for PHP5, uses libmemcached
php-net-dns2 - PHP5 Resolver library used to communicate with a DNS server
phpunit - Unit testing suite for PHP5
```

Here not anymore. Fresh install.

**Comment by Wouter0100** [comment]
Hmm, it doesn't seems to work properly. Let me check.

**Comment by Wouter0100** [comment]
Seems to be because of puppetlabs/puppetlabs-apache#1430. The class we use, `::apache::mod::php`, currently only supports php5.

**Comment by Wouter0100** [comment]
puppetlabs/puppetlabs-apache#1430 seems to work flawless, the only leftover issue for 16.04 is when loading phpmyadmin:

```
[Thu Apr 21 23:24:00.313534 2016] [:error] [pid 6148] [client 127.0.0.1:36052] phpmyadmin: Failed to load /var/lib/phpmyadmin/blowfish_secret.inc.php Check group www-data has read access and open_basedir restrictions.
[Thu Apr 21 23:24:00.313584 2016] [:error] [pid 6148] [client 127.0.0.1:36052] phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions.
[Thu Apr 21 23:24:00.313598 2016] [:error] [pid 6148] [client 127.0.0.1:36052] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Apr 21 23:24:00.314590 2016] [:error] [pid 6148] [client 127.0.0.1:36052] PHP Fatal error:  require_once(): Failed opening required '/usr/share/php/php-gettext/gettext.inc' (include_path='.:/usr/share/php') in /usr/share/phpmyadmin/libraries/select_lang.lib.php on line 477
```

**Comment by Marlinc** [comment]
Thank you!

**Pull request merged**
